[package]
name = "xxx"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.24"
imageproc = "0.23"
rusttype = "0.9"
windows = { version = "0.58", features = [
    "Win32_Graphics_Gdi",
    "Win32_Storage_Xps",
    "Win32_Foundation",
] }
